app/accounts/urls.py
#encoding: utf-8

from django.urls import path, reverse_lazy
from accounts.views import (create_account, list_account, 
                            active_account, edit_profile, edit_password, 
                            detail_profile, reset_password, confirm_reset_password,
                            create_user, list_user, edit_user, delete_user, edit_password_user) 
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns=[
    path('sign_in/',LoginView.as_view(template_name='accounts/auth/login.html'), name='login'),
    path('sign_out/',LogoutView.as_view(next_page=reverse_lazy('accounts:login')),name='logout'),
    path('create_account/',create_account, name='create_account'),
    path('list_account/',list_account, name='list_account'),
    path('active_account/<pk>',active_account, name='active_account'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('edit_password/',edit_password, name='edit_password'),
    path('detail_profile/',detail_profile, name='detail_profile'),
    path('reset_password/', reset_password, name='reset_password'),
    path('confirm_reset_password/',confirm_reset_password, name='confirm_reset_password'),
    path('create_user/',create_user, name='create_user'),
    path('list_user/',list_user, name='list_user'),
    path('edit_user/<pk>',edit_user, name='edit_user'),
    path('delete_user/<pk>',delete_user, name='delete_user'),
    path('edit_password_user/<pk>',edit_password_user, name='edit_password_user'),
]

app/conf/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
	path('', RedirectView.as_view(url='/main/',permanent=True), name='index'),
    path('security/', admin.site.urls),
	path('main/', include(('main.urls', 'main'), namespace='main')),
	path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
	path('wallet/', include(('wallet.urls', 'wallet'), namespace='wallet')),
	path('i18n/', include('django.conf.urls.i18n')),
]

app/main/urls.py
from django.urls import path
from main.views import home, graphics, alerts, payment, balance, set_left_menu_session

urlpatterns=[
    path('', home, name='home'),
    path('graphics/', graphics, name='graphics'),
    path('alerts/', alerts, name='alerts'),
    path('payment/', payment, name='payment'),
    path('balance/', balance, name='balance'),
    path('set_left_menu_session/', set_left_menu_session, name='set_left_menu_session'),
]

app/accounts/views.py
#encoding: utf-8

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.views.generic import View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import RequestContext
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth import update_session_auth_hash
from accounts.models import Profile, PasswordReset, User
from accounts.permissions import PermissionsAccountMixin, PermissionsUserMixin
from accounts.forms import EditUserForm, ProfileForm, AddUserForm, AccountForm, PasswordResetForm
from accounts.utils import AccountUtils
from main.utils import apps_permissions, get_list_permissions
from main.decorators import ajax_required
from main.mail import send_mail_confirm_account



class AccountView(View):

    template_name = 'accounts/register/create_account.html'
    success_url = reverse_lazy('accounts:create_account')

    def get(self, request):
        context = {'form_profile': ProfileForm, 'form_user': AddUserForm,
                   'form_account': AccountForm, 'url_payment': reverse_lazy('main:payment')}
        return render(self.request, self.template_name, context)

    def post(self, request):
        form_profile = ProfileForm(self.request.POST or None)
        form_user = AddUserForm(self.request.POST or None)
        form_account = AccountForm(self.request.POST or None)

        if form_profile.is_valid() and form_user.is_valid() and form_account.is_valid():
            profile = form_profile.save(commit=False)
            user = form_user.save(profile=profile, commit=False)
            user.account = form_account.save()
            user.save()

            profile.user = user
            profile.order = Profile.ORDER_CHOICE[0][0]
            profile.save()

            account = AccountUtils(profile)
            account.active_account(True)
            account.add_user_group('customers')
            account.save_account()

            messages.info(self.request,'Cadastro criado com sucesso, aguarde para ser redirecionado '+\
                          'para tela de pagamento ou clique')

            try:
                send_mail_confirm_account(profile)
            except Exception as Error:
                pass

            return HttpResponseRedirect(self.success_url)

        context = {'form_profile': form_profile, 'form_user': form_user,
                   'form_account': form_account, 'url_payment': reverse_lazy('main:payment')}
        return render(self.request, self.template_name, context)


class AccountListView(PermissionsAccountMixin, ListView):

    model = Profile
    paginate_by = 5
    template_name = 'accounts/register/list_account.html'
    success_url = reverse_lazy('accounts:login')
    required_permissions = get_list_permissions(model, permission_list=['all'])


class UserListView(PermissionsUserMixin, ListView):

    model = User
    paginate_by = 5
    template_name = 'accounts/user/list_user.html'
    success_url = reverse_lazy('accounts:login')
    required_permissions = get_list_permissions(model, permission_list=['all'])


@login_required
@user_passes_test(lambda u: u.groups.filter(name='customers').exists(),
                                            login_url='accounts:logout')
def edit_user(request, pk):
    template_name = 'accounts/user/edit_user.html'
    user = get_object_or_404(User, pk=pk, account=request.user.account)
    form_user = EditUserForm(request.POST or None, instance=user)
    form_profile = ProfileForm(request.POST or None,
                                  instance=get_object_or_404(Profile, user=user))
    if form_user.is_valid() and form_profile.is_valid():
        form_user.save(profile=form_profile.save())
        messages.success(request, 'Os dados da sua conta foram alterados com sucesso')
    context = {'form_profile':form_profile, 'form_user':form_user, 'object_name':'User',
               'apps':apps_permissions(request),'label_app':'Accounts', 'object':user}
    return render(request, template_name, context)


class UserDeleteView(PermissionsUserMixin, DeleteView):

    model = User
    template_name = 'accounts/user/user_confirm_delete.html'
    success_url = reverse_lazy('accounts:list_user')
    required_permissions = get_list_permissions(model, permission_list=['all'])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(self.request, 'Usuário removido')
        except Exception as Error:
            messages.error(self.request, 'Tente novamente, ocorreu um erro')
        return HttpResponseRedirect(self.success_url)


delete_user = UserDeleteView.as_view()
list_user = UserListView.as_view()
list_account = AccountListView.as_view()
create_account = AccountView.as_view()


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='accounts:logout')
def active_account(request, pk):
    account = AccountUtils(get_object_or_404(Profile, pk=pk))
    try:
        if account.check_status():
            messages.warning(request, 'Esta conta já está ativa.')
            return HttpResponseRedirect(reverse_lazy('accounts:list_account'))
        account.active_payment()
        messages.success(request, 'Conta ativada')
    except Exception as Error:
        account.roll_back()
        messages.error(request, Error)
    return HttpResponseRedirect(reverse_lazy('accounts:list_account'))


@login_required
@ajax_required
def edit_password(request):
    template_name = 'accounts/user/edit_password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST or None, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Senha alterada com sucesso')
            update_session_auth_hash(request, form.user)
            return HttpResponse('ok')
    else:
        form = PasswordChangeForm(user=request.user)
    context = {"form": form}
    return render(template_name, context, context_instance=RequestContext(request))


@login_required
@ajax_required
@user_passes_test(lambda u: u.groups.filter(name='customers').exists(),
                                            login_url='accounts:logout')
def edit_password_user(request, pk):
    template_name = 'accounts/user/edit_password_user.html'
    user = get_object_or_404(User, pk=pk, account=request.user.account)
    if request.method == 'POST':
        form = SetPasswordForm(user=user, data=request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Senha alterada com sucesso')
            update_session_auth_hash(request, form.user)
            return HttpResponse('ok')
    else:
        form = SetPasswordForm(user=user, data=request.POST or None)
    context = {"object":user, "form": form}
    return render(template_name, context, context_instance=RequestContext(request))


@login_required
def edit_profile(request):
    template_name = 'accounts/user/edit_profile.html'
    form_user = EditUserForm(request.POST or None, instance=request.user)
    form_profile = ProfileForm(request.POST or None,
                                  instance=get_object_or_404(Profile, user=request.user))
    if form_user.is_valid() and form_profile.is_valid():
        form_user.save(profile=form_profile.save())
        messages.success(request, 'Os dados do seu perfil foram alterados com sucesso')
        return redirect('accounts:edit_profile')
    context = {'form_profile':form_profile, 'form_user':form_user,
               'object_name':'Profile', 'apps':apps_permissions(request),'label_app':'None',}
    return render(request, template_name, context)


@login_required
def detail_profile(request):
    context = {'profile': get_object_or_404(Profile, user=request.user),
               'app_label':None, 'object_name':None, 'apps':apps_permissions(request)}
    template_name = 'accounts/user/detail_profile.html'
    return render(request, template_name, context)


@login_required
@user_passes_test(lambda u: u.groups.filter(name='customers').exists(),
                                            login_url='accounts:logout')
def create_user(request):
    template_name = 'accounts/user/create_user.html'
    form_user = AddUserForm(request.POST or None)
    form_profile = ProfileForm(request.POST or None)

    if form_user.is_valid() and form_profile.is_valid():
        try:
            profile = form_profile.save(commit=False)
            user = form_user.save(profile=profile, commit=False)
            user.account = request.user.account
            user.is_active = True
            user.save()
            profile.user = user
            profile.order = Profile.ORDER_CHOICE[1][0]
            profile.status_profile = True
            profile.save()
            accounts = AccountUtils(profile)
            accounts.add_user_group('users')
            messages.success(request, 'Usuário criado com sucesso')
            return redirect('accounts:list_user')
        except Exception as Error:
            messages.error(request, 'Ocorreu um erro, tente novamente')

    context = {'form_profile':form_profile, 'form_user':form_user,
               'object_name':'User', 'apps':apps_permissions(request),'label_app':'Accounts',}
    return render(request, template_name, context)


@ajax_required
def reset_password(request):
    template_name = 'accounts/auth/reset_password.html'

app/conf/templates/accounts/user/create_user.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}

{% block extra_styles %}
	<link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li><a href="{% url 'accounts:list_user' %}"><i class="fa fa-user fa-fw"></i> Usuários</a></li>
			<li class="active"><i class="fa fa-plus fa-fw"></i> Novo Usuário</li>
		</ol>
		<!-- ROW CREATE USER -->
		<div class="row" id="create_user">
			<div class="col-md-12">

				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Novo Usuário</h3>
						<div class='right'>
							<ul class="list-inline">
								<li>
									<a href='{% url "accounts:list_user" %}'><i style="font-size:15px;" class='lnr lnr-cross'></i></a>
								</li>
							</ul>
						</div>
					</div>

					<div class="panel-body">

						{% include "messages.html" %}

						<div class='col-md-12'>
							<div class="profile-detail">

								<form name='create_user' method='POST' class="accounts-user">
								{% csrf_token %}
									<div class='row'>
										<div class='col-md-4 col-md-offset-2'>

											<div class='input-group {% if form_profile.first_name.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-id-card fa-fw'></i>
												</div>
												{{ form_profile.first_name|placeholder:"Nome" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.first_name.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_profile.last_name.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-id-card fa-fw'></i>
												</div>
												{{ form_profile.last_name|placeholder:"Sobrenome" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.last_name.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_profile.birthday.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-birthday-cake fa-fw'></i>
												</div>
												{{ form_profile.birthday|addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.birthday.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_user.email.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-envelope fa-fw'></i>
												</div>
												{{ form_user.email|placeholder:"usuario@exemplo.com" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_user.email.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_user.password1.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-key fa-fw'></i>
												</div>
												{{ form_user.password1|placeholder:"senha" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_user.password1.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_user.password2.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-lock fa-fw'></i>
												</div>
												{{ form_user.password2|placeholder:"Repetir Senha" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_user.password2.errors|join:"<br \>" }}</span>

										</div><!-- EMD COL-MD-4 -->

										<div class='col-md-4'>
											<div class='input-group {% if form_profile.description.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-pencil fa-fw'></i>
												</div>
												{{ form_profile.description|placeholder:"Informações do perfil" |textarea:"6" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.description.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_profile.state.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-map-marker fa-fw'></i>
												</div>
												{{ form_profile.state|addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.state.errors|join:"<br \>" }}</span>

											<div class='input-group {% if form_profile.url.errors %}has-error{% endif %}'>
												<div class='input-group-addon'>
													<i class='fa fa-bookmark fa-fw'></i>
												</div>
												{{ form_profile.url|placeholder:"Site / Rede Social" |addcss:"form-control" }}
											</div>
											<span class="error text-danger">{{ form_profile.url.errors|join:"<br \>" }}</span>

										</div><!-- END COL-MD-4 -->
									</div><!-- END ROW -->


									<div class="text-center">
										<button class='btn btn-primary' type='submit' name='new_user' id='id_new_user'>
											Salvar
										</button>

										<a class='btn btn-danger' href="{% url 'accounts:list_user' %}" name='close_new_user' id='id_close_new_user'>
											Fechar
										</a>
									</div>

								</form>
							</div>
						</div>
					</div>

				</div><!-- END PANEL -->
			</div><!-- END COL-MD-12 -->

		</div><!-- END ROW CREATE USER -->
	</div><!-- END CONTAINER-FLUID -->
{% endblock %}

{% block extra_scripts %}
	<script src="{% static 'js/libs/moment.min.js' %}"></script>
	<script src="{% static 'js/libs/daterangepicker.js' %}"></script>
	<script src="{% static 'js/accounts.js' %}"></script>
{% endblock %}

app/conf/templates/accounts/user/detail_profile.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}

{% block content %}
	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li class="active"><i class="fa fa-user fa-fw"></i> Detalhar Perfil</li>
		</ol>

		<div class="row" id="detail_profile">
			<div class="col-md-12">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Detalhar Perfil</h3>
						<div class='right'>
							<ul class="list-inline">
								<li><a href="{% url 'main:home' %}"><i style="font-size:15px;" class='lnr lnr-cross'></i></a></li>
							</ul>
						</div>
					</div>
					<div class="panel-body">
						<div class='col-md-8 col-md-offset-2'>
							<div class="profile-detail">
								<div class="profile-info">
									<ul class="list-unstyled list-justify">
										<li><i class='fa fa-user fa-fw'></i> Nome <span>{{ profile.first_name }} {{ profile.last_name }}</span></li>
										<li><i class='fa fa-birthday-cake fa-fw'></i> Aniversário <span>{{ profile.birthday }}</span></li>
										<li><i class='fa fa-map-marker fa-fw'></i> Estado <span>{{ profile.state }}</span></li>
										<li><i class='fa fa-envelope fa-fw'></i> E-mail <span>{{ profile.user.email }}</span></li>
										<li><i class='fa fa-bookmark fa-fw'></i> Website <span><a href="{{ profile.url }}">{{ profile.url }}</a></span></li>
									</ul>
								</div>
								<div class="profile-info">
									<h4 class="heading">Informações</h4>
									<p>{{ profile.description }}</p>
								</div>
								<div class="text-center">
									<a name="detail_profile" id="id_detail_profile" href="{{ profile.user.get_edit_profile }}" class="btn btn-primary">Editar</a>
									<a href="{% url 'main:home' %}" class='btn btn-danger' name='close_detail_profile' id='id_close_detail_profile'>Fechar</a>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div><!-- END ROW DETAIL PROFILE -->
	</div><!-- END CONTAINER-FLUID -->
{% endblock %}

app/conf/templates/accounts/user/edit_password.html
{% load static %}

<div class="modal-header">
  <button aria-hidden="true" data-dismiss="modal" class="close" type="button"><i style="font-size:15px;" class='lnr lnr-cross'></i></button>
  <h4 class="modal-title">Editar Senha</h4>
</div>

<div class="modal-body">
	<div id="edit_password_profile">
		<form method="post" action="{% url 'accounts:edit_password' %}" role="form" id='form_edit_password' class="form-bordered form-modal-edit-password" success-url="{{ request.user.get_edit_profile }}">
		{% csrf_token %}

			{% include "messages.html" %}

			<div class="row">
				<div class='col-md-12'>
					<div class="form-group {% if form.old_password.errors %}has-error{% endif %}">
						<label class="col-sm-4 control-label" for="id_old_password">* Senha:</label>
						<div class="col-sm-8">
							<input class="form-control" id="id_old_password" name="old_password" type="password" placeholder="Senha Atual">
							<span class="error text-danger">{{ form.old_password.errors|join:"<br \>" }}</span>
						</div>
					</div>

					<div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
						<label class="col-sm-4 control-label" for="id_new_password1">* Nova Senha:</label>
						<div class="col-sm-8">
							<input class="form-control" id="id_new_password1" name="new_password1" type="password" placeholder="Nova Senha">
							<span class="error text-danger">{{ form.new_password1.errors|join:"<br \>" }}</span>
						</div>
					</div>

					<div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
						<label class="col-sm-4 control-label" for="id_new_password2">* Repetir Senha:</label>
						<div class="col-sm-8">
							<input class="form-control" id="id_new_password2" name="new_password2" type="password" placeholder="Repetir Senha">
							<span class="error text-danger">{{ form.new_password2.errors|join:"<br \>" }}</span>
						</div>
					</div>
				</div><!-- END COL-MD-12 -->
			</div><!--END ROW -->

			<div class="row">
				<div class="col-md-8 col-md-offset-4" style="margin-top:2%;">
					<button type="submit" class="btn btn-primary btn-metro" id='id_edit_password'>Editar</button>
					<button aria-hidden="true" data-dismiss="modal" class="btn btn-danger" type="button">Fechar</button>
				</div>
			</div><!-- END ROW -->

		</form><!--END FORM -->
	</div>
</div><!--modal-body-->

app/conf/templates/accounts/user/edit_password_user.html
{% load static %}

<div class="modal-header">
  <button aria-hidden="true" data-dismiss="modal" class="close" type="button"><i style="font-size:15px;" class='lnr lnr-cross'></i></button>
  <h4 class="modal-title">Editar Senha</h4>
</div>

<div class="modal-body">
	<div id="edit_password_user">
		<form role="form" method="post" action="{% url 'accounts:edit_password_user' object.pk %}" id='form_edit_password_user' class="form-bordered form-modal-edit-password" success-url="{{ object.get_edit_user }}">
		{% csrf_token %}

			{% include "messages.html" %}

			<div class="row">
				<div class='col-md-12'>
					<div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
						<label class="col-sm-4 control-label" for="id_new_password1">* Nova Senha:</label>
						<div class="col-sm-8">
							<input class="form-control" id="id_new_password1" name="new_password1" type="password" placeholder="Nova Senha">
							<span class="error text-danger">{{ form.new_password1.errors|join:"<br \>" }}</span>
						</div>
					</div>

					<div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
						<label class="col-sm-4 control-label" for="id_new_password2">* Repetir Senha:</label>
						<div class="col-sm-8">
							<input class="form-control" id="id_new_password2" name="new_password2" type="password" placeholder="Repetir Senha">
							<span class="error text-danger">{{ form.new_password2.errors|join:"<br \>" }}</span>
						</div>
					</div>
				</div><!-- END COL-MD-12 -->
			</div><!--END ROW -->

			<div class="row">
				<div class="col-md-8 col-md-offset-4" style="margin-top:2%;">
					<button type="submit" class="btn btn-primary btn-metro" id='id_edit_password'>Editar</button>
					<button aria-hidden="true" data-dismiss="modal" class="btn btn-danger" type="button">Fechar</button>
				</div>
			</div><!-- END ROW -->

		</form><!--END FORM -->
	</div>
</div><!--modal-body-->

app/conf/templates/accounts/user/list_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li class='active'><i class="fa fa-user fa-fw"></i> Usuários</li>
		</ol>

		<!-- ROW LIST USER -->
		<div class="row" id="list_user">
			<div class="col-md-12">

				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Usuários</h3>
						<div class='right'>
							<ul class="list-inline">
								<li>
									<form class="form-inline" method='get'>
										<label class="sr-only" for="date">Data</label>
										<div class="input-group">
											<div class="input-group-addon">
												<i class="fa fa-calendar"></i>
											</div>
											<select class="form-control" name="status_user" id="id_status_user">
												<option {% if request.GET.status_user == 'all' %}selected{% endif %} value="all">todos</option>
												<option {% if request.GET.status_user == 'True' %}selected{% endif %} value="True">ativo</option>
												<option {% if request.GET.status_user == 'False' %}selected{% endif %} value="False">bloqueado</option>
											</select>
										</div>
										<button type="submit"><i class='lnr lnr-magnifier'></i></button>
									</form>
								</li>
								<li>
									<a href="{% url 'accounts:create_user' %}"><i style="font-size:15px;" class='lnr lnr-plus-circle'></i></a>
								</li>
							</ul>
						</div>
					</div>

					<div class="panel-body">

						{% include "messages.html" %}

						{% if not object_list %}
							<div class='empty-object'>
								<center>
									<h3>Não existem usuários cadastrados</h3>
								</center>
							</div>
						{% else %}
							<div class="table-responsive">
								<table class="table table-striped mb30">
									<thead>
										<tr>
											<th>Nome</th>
											<th>E-mail</th>
											<th>Status</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
										{% for user_list in object_list %}
											
											<tr>
												<td>{{ user_list.first_name }} {{ user_list.profile.last_name }}</td>
												<td>{{ user_list.email }}</td>
												<td>
												{% if user_list.is_active %}
													<i style='color:green;' class='fa fa-check-circle'></i>
												{% else %}
													<i style='color:red;' class='fa fa-minus-circle'></i>
												{% endif %}
												</td>
												<td class="actions">
													<a href="{{ user_list.get_edit_user }}"><i class="lnr lnr-pencil"></i></a>
													<a href="{{ user_list.get_delete_user }}"><i class="lnr lnr-trash"></i></a>
												</td>
											</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>

							<nav><!--nav-->
								<ul class="pagination pagination-centered" style='margin: 5px 0 7px;'><!--ul pagination pagination-centered -->
									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled{% endif %}' href="?page=1" title=""><<</a>
									</li>

									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled {% endif %}' href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" title=""><</a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %} btn disabled{% endif %}' href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" title="">></a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %}btn disabled{% endif %}' href="?page={{paginator.num_pages}}" title="">>></a>
									</li>
								</ul><!--ul pagination pagination-centered -->
							</nav><!--nav-->
							<small>{{ page_obj.number }} de {{paginator.num_pages}}</small>

						{% endif %}
					</div>

				</div>
			</div>

		</div><!-- END LIST USER -->
	</div><!-- END CONTAINER-FLUID -->
{% endblock %}