app/accounts/urls.py
#encoding: utf-8

from django.urls import path, reverse_lazy
from accounts.views import (create_account, list_account, 
                            active_account, edit_profile, edit_password, 
                            detail_profile, reset_password, confirm_reset_password,
                            create_user, list_user, edit_user, delete_user, edit_password_user) 
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns=[
    path('sign_in/',LoginView.as_view(template_name='accounts/auth/login.html'), name='login'),
    path('sign_out/',LogoutView.as_view(next_page=reverse_lazy('accounts:login')),name='logout'),
    path('create_account/',create_account, name='create_account'),
    path('list_account/',list_account, name='list_account'),
    path('active_account/<pk>',active_account, name='active_account'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('edit_password/',edit_password, name='edit_password'),
    path('detail_profile/',detail_profile, name='detail_profile'),
    path('reset_password/', reset_password, name='reset_password'),
    path('confirm_reset_password/',confirm_reset_password, name='confirm_reset_password'),
    path('create_user/',create_user, name='create_user'),
    path('list_user/',list_user, name='list_user'),
    path('edit_user/<pk>',edit_user, name='edit_user'),
    path('delete_user/<pk>',delete_user, name='delete_user'),
    path('edit_password_user/<pk>',edit_password_user, name='edit_password_user'),
]

app/conf/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
	path('', RedirectView.as_view(url='/main/',permanent=True), name='index'),
    path('security/', admin.site.urls),
	path('main/', include(('main.urls', 'main'), namespace='main')),
	path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
	path('wallet/', include(('wallet.urls', 'wallet'), namespace='wallet')),
	path('i18n/', include('django.conf.urls.i18n')),
]

app/main/urls.py
from django.urls import path
from main.views import home, graphics, alerts, payment, balance, set_left_menu_session

urlpatterns=[
    path('', home, name='home'),
    path('graphics/', graphics, name='graphics'),
    path('alerts/', alerts, name='alerts'),
    path('payment/', payment, name='payment'),
    path('balance/', balance, name='balance'),
    path('set_left_menu_session/', set_left_menu_session, name='set_left_menu_session'),
]

app/accounts/models.py
#coding: utf-8

import re
from django.db.models import Q
from django.db import models
from django.conf import settings
from django.core import validators
from accounts.localflavor.br.br_states import STATE_CHOICES
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.urls import reverse



class Account(models.Model):

    id_account = models.AutoField(primary_key=True, verbose_name=u'Cod Account', db_column='id_account')
    cpf = models.CharField(max_length=30, verbose_name=u'Cpf', db_column='cpf', unique=True)
    status_account = models.BooleanField(verbose_name=u'Status', default=False, db_column='status_account')
    status_payment = models.BooleanField(verbose_name=u'Status Payments', default=False, db_column='status_payment')
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')
    created_at = models.DateTimeField(verbose_name=u'Criado em', auto_now_add=True)

    def __unicode__(self):
        return u'%s' % self.cpf

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Account'
        ordering=['-created_at']
        db_table='account'
        permissions = (
                ('add_new_account', 'add account'),
                ('list_new_account', 'list account'),
                ('delete_new_account', 'delete account'),
                ('change_new_account', 'change account'),
                ('detail_new_account', 'detail account'),
        )



class UserManager(models.Manager):

    def list_user(self, user):
        qs = super(UserManager, self).get_queryset().filter(~Q(pk=user.pk))
        if not user.is_superuser and user.is_active:
            qs = qs.filter(account=user.account)
        elif user.is_superuser:
            qs = qs
        else:
            qs = qs.none()
        return qs

    def get_by_natural_key(self, email):
        return self.get(email=email)


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        verbose_name=u'Nome de Usuário', max_length=30,
        validators=[validators.RegexValidator(re.compile('[a-zA-Z]'),
            'O nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField(verbose_name=u'E-mail', unique=True)
    is_active = models.BooleanField(verbose_name=u'Está ativo?', default=False)
    is_staff = models.BooleanField(verbose_name=u'É da equipe?', default=False)
    date_joined = models.DateTimeField(verbose_name=u'Data de Entrada', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')
    account = models.ForeignKey(Account, verbose_name='Conta', related_name='user_account',
                                on_delete=models.CASCADE, null=False)
    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __unicode__(self):
        return u'%s' % self.email

    def natural_key(self):
        return (self.email)

    @property
    def name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return str(self)

    def get_edit_profile(self):
        return reverse('accounts:edit_profile', kwargs={})

    def get_detail_profile(self):
        return reverse('accounts:detail_profile', kwargs={})

    def get_edit_user(self):
        return reverse('accounts:edit_user', kwargs={'pk':self.pk})

    def get_delete_user(self):
        return reverse('accounts:delete_user', kwargs={'pk':self.pk})

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'User'
        ordering = ['-date_joined']
        db_table='user'
        permissions = (
                ('add_new_user', 'add user'),
                ('list_new_user', 'list user'),
                ('delete_new_user', 'delete user'),
                ('change_new_user', 'change user'),
                ('detail_new_user', 'detail user'),
        )



class PasswordReset(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='resets_user',
                             on_delete=models.CASCADE, null=False)
    key = models.CharField(verbose_name=u'Chave', max_length=100, unique=True)
    created_at = models.DateTimeField(verbose_name=u'Criado em', auto_now_add=True)
    confirmed = models.BooleanField(verbose_name=u'Confirmado?', default=False)

    def __unicode__(self):
        return u'%s' % self.user

    class Meta:
        verbose_name = 'New Password'
        verbose_name_plural = 'New Password'
        ordering = ['-created_at']
        db_table='passwordreset'
        permissions = (
                ('add_new_password', 'add password'),
                ('list_new_password', 'list password'),
                ('delete_new_password', 'delete password'),
                ('change_new_password', 'change password'),
                ('detail_new_password', 'detail password'),
        )



class ProfileManager(models.Manager):

    def list_account(self, user):
        qs = super(ProfileManager, self).get_queryset().filter(~Q(user=user))
        if not user.is_superuser and user.is_active:
            qs = qs.filter(user__account=user.account)
        elif user.is_superuser:
            qs = qs
        else:
            qs = qs.none()
        return qs


class Profile(models.Model):

    ORDER_CHOICE = ((0, 'super'),(1, 'user'))

    id_profile = models.AutoField(primary_key=True, verbose_name=u'id_profile', db_column='id_profile')
    first_name = models.CharField(max_length=50, verbose_name=u'Nome', db_column='first_name',
                                  validators=[validators.RegexValidator(re.compile('[A-Za-z]'),
                                             'O nome de usuário só pode conter letras', 'invalid')])
    last_name = models.CharField(max_length=100, verbose_name=u'Sobrenome', db_column='last_name')
    status_profile = models.BooleanField(verbose_name=u'Status', default=False, db_column='status_profile')
    state = models.CharField(choices=STATE_CHOICES, max_length=10, verbose_name=u'Estado', db_column='state')
    created_at = models.DateTimeField(verbose_name=u'Data de criação', auto_now_add=True, db_column='date_created')
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')
    birthday = models.DateField(verbose_name=u'Aniversario', db_column='birthday', blank=True, null=True)
    url = models.CharField(max_length=100, verbose_name=u'Site', db_column='url', blank=True, null=True)
    description = models.TextField(db_column='description', blank=True, null=True, verbose_name=u'Descricao')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='Usuário', related_name='profile_user',
                                on_delete=models.CASCADE, null=False)
    order = models.IntegerField(choices=ORDER_CHOICE, verbose_name=u'Ordem', db_column='order',
                                default=ORDER_CHOICE[1][0])

    objects = ProfileManager()

    def __unicode__(self):
        return u'%s' % self.first_name

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return str(self)

    def active_account(self):
        return reverse('accounts:active_account', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profile'
        ordering=['-created_at']
        db_table='profile'
        permissions = (
                ('add_new_profile', 'add profile'),
                ('list_new_profile', 'list profile'),
                ('delete_new_profile', 'delete profile'),
                ('change_new_profile', 'change profile'),
                ('detail_new_profile', 'detail profile'),
        )

app/accounts/localflavor/br/forms.py
#encoding: utf-8

from django.core.validators import EMPTY_VALUES
from django.forms import ValidationError
from django.forms.fields import Field, RegexField, CharField, Select
from django.utils.encoding import smart_text
from django.utils.translation import ugettext_lazy as _
import re


phone_digits_re = re.compile(r'^(\d{2})[-\.]?(\d{4})[-\.]?(\d{4})$')



class BRZipCodeField(RegexField):

    default_error_messages = {
        'invalid': _('Enter a zip code in the format XXXXX-XXX.'),
    }

    def __init__(self, max_length=None, min_length=None, *args, **kwargs):
        super(BRZipCodeField, self).__init__(r'^\d{5}-\d{3}$',
            max_length, min_length, *args, **kwargs)



class BRPhoneNumberField(Field):

    default_error_messages = {
        'invalid': _('Phone numbers must be in XX-XXXX-XXXX format.'),
    }

    def clean(self, value):
        super(BRPhoneNumberField, self).clean(value)
        if value in EMPTY_VALUES:
            return u''
        value = re.sub('(\(|\)|\s+)', '', smart_text(value))
        m = phone_digits_re.search(value)
        if m:
            return u'%s-%s-%s' % (m.group(1), m.group(2), m.group(3))
        raise ValidationError(self.error_messages['invalid'])



class BRStateSelect(Select):

    def __init__(self, attrs=None):
        from br_states import STATE_CHOICES
        super(BRStateSelect, self).__init__(attrs, choices=STATE_CHOICES)



class BRStateChoiceField(Field):

    widget = Select
    default_error_messages = {
        'invalid': _(u'Select a valid brazilian state. That state is not one of the available states.'),
    }

    def __init__(self, required=True, widget=None, label=None,
                 initial=None, help_text=None):
        super(BRStateChoiceField, self).__init__(required, widget, label,
                                                 initial, help_text)
        from br_states import STATE_CHOICES
        self.widget.choices = STATE_CHOICES

    def clean(self, value):
        value = super(BRStateChoiceField, self).clean(value)
        if value in EMPTY_VALUES:
            value = u''
        value = smart_text(value)
        if value == u'':
            return value
        valid_values = set([smart_text(k) for k, v in self.widget.choices])
        if value not in valid_values:
            raise ValidationError(self.error_messages['invalid'])
        return value

def DV_maker(v):
    if v >= 2:
        return 11 - v
    return 0



class BRCPFField(CharField):

    default_error_messages = {
        'invalid': _("Invalid CPF number."),
        'max_digits': _("This field requires at most 11 digits or 14 characters."),
        'digits_only': _("This field requires only numbers."),
    }

    def __init__(self, max_length=14, min_length=11, *args, **kwargs):
        super(BRCPFField, self).__init__(*args, **kwargs)

    def clean(self, value):
        """
        Value can be either a string in the format XXX.XXX.XXX-XX or an
        11-digit number.
        """
        value = super(BRCPFField, self).clean(value)
        if value in EMPTY_VALUES:
            return u''
        orig_value = value[:]
        if not value.isdigit():
            value = re.sub("[-\.]", "", value)
        try:
            int(value)
        except ValueError:
            raise ValidationError(self.error_messages['digits_only'])
        if len(value) != 11:
            raise ValidationError(self.error_messages['max_digits'])
        orig_dv = value[-2:]

        new_1dv = sum([i * int(value[idx]) for idx, i in enumerate(range(10, 1, -1))])
        new_1dv = DV_maker(new_1dv % 11)
        value = value[:-2] + str(new_1dv) + value[-1]
        new_2dv = sum([i * int(value[idx]) for idx, i in enumerate(range(11, 1, -1))])
        new_2dv = DV_maker(new_2dv % 11)
        value = value[:-1] + str(new_2dv)
        if value[-2:] != orig_dv:
            raise ValidationError(self.error_messages['invalid'])

        return orig_value



class BRCNPJField(Field):

    default_error_messages = {
        'invalid': _("Invalid CNPJ number."),
        'digits_only': _("This field requires only numbers."),
        'max_digits': _("This field requires at least 14 digits"),
    }

    def clean(self, value):
        """
        Value can be either a string in the format XX.XXX.XXX/XXXX-XX or a
        group of 14 characters.
        """
        value = super(BRCNPJField, self).clean(value)
        if value in EMPTY_VALUES:
            return u''
        orig_value = value[:]
        if not value.isdigit():
            value = re.sub("[-/\.]", "", value)
        try:
            int(value)
        except ValueError:
            raise ValidationError(self.error_messages['digits_only'])
        if len(value) != 14:
            raise ValidationError(self.error_messages['max_digits'])
        orig_dv = value[-2:]

        new_1dv = sum([i * int(value[idx]) for idx, i in enumerate(range(5, 1, -1) + range(9, 1, -1))])
        new_1dv = DV_maker(new_1dv % 11)
        value = value[:-2] + str(new_1dv) + value[-1]
        new_2dv = sum([i * int(value[idx]) for idx, i in enumerate(range(6, 1, -1) + range(9, 1, -1))])
        new_2dv = DV_maker(new_2dv % 11)
        value = value[:-1] + str(new_2dv)
        if value[-2:] != orig_dv:
            raise ValidationError(self.error_messages['invalid'])

        return orig_value

app/conf/templates/accounts/register/confirm_reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Payments</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

        <!-- GOOGLE FONTS -->
        <link rel="stylesheet" href="{% static 'css/fonts-google/css/font-googleapi.css' %}">
        <!-- ICONS -->
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">

        <!-- VENDOR CSS -->
        <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}">
        <!-- MAIN CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
        <!-- CUSTOM CSS -->
        <link rel="stylesheet" href="{% static 'css/custom_styles.css' %}">
    </head>
    <body class='layout-fullwidth'>
        <div class="container-fluid">
            <div class="row" id="confirm_reset_password">
                <div class='col-md-5 col-md-offset-3'>
                    <h2> Resetar Senha</h2>
                    <form role="form" method='post' class="form-bordered">
                    {% csrf_token %}

                        <div class='row'>
                            <div class='col-md-11'>
                                {% include "messages.html" %}
                            </div>
                        </div><!-- END ROW -->

                        <div class='row'>
                            <div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
                                <label class="col-sm-2 control-label" for="id_new_password1">* Nova Senha:</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="id_new_password1" name="new_password1" type="password"placeholder="Nova Senha">
                                    <span class="error text-danger">{{ form.new_password1.errors|join:"<br \>" }}</span>
                                </div>
                            </div>
                        </div><!-- END ROW -->

                        <div class='row'>
                            <div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
                                <label class="col-sm-2 control-label" for="id_new_password2">* Verificar senha:</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="id_new_password2" name="new_password2" type="password"placeholder="Verificar Senha">
                                    <span class="error text-danger">{{ form.new_password2.errors|join:"<br \>" }}</span>
                                </div>
                            </div>
                        </div><!-- END ROW -->

                        <div class='row'>
                            <div class="text-center">
                                <div class="col-md-8" style="margin-top:2%;">
                                    <button id="reset_password" name="id_reset_password" type="submit" class="btn btn-primary btn-metro">Editar</button>
                                        <a id="close_reset_password" name="id_close_reset_password" class="btn btn-danger" href="{% url 'accounts:login' %}">Fechar</a>
                                </div>
                            </div>
                        </div><!-- END ROW -->

                    </form><!--form-->
                </div>
            </div><!-- END confirm_reset_password -->
        </div><!-- END CONTAINER-FLUID -->

        <!-- JS -->
        <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>
        <!-- END JS -->
    </body>
</html>

app/conf/templates/accounts/register/list_account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li><i class="fa fa-address-book fa-fw"></i> Contas</li>
		</ol>

		<!-- ROW LIST ACCOUNTS -->
		<div class="row" id="list_accounts">
			<div class="col-md-12">

				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Contas</h3>
						<div class='right'>
							<ul class="list-inline">
								<li>
									<form class="form-inline" method="get">
										<div class="input-group">
											<div class="input-group-addon">
												<i class="fa fa-tags" aria-hidden="true"></i>
											</div>
											<select class="form-control" name="order">
												<option {% if request.GET.order == 'all' %}selected{% endif %} value="all">all</option>
												<option {% if request.GET.order == '0' %}selected{% endif %} value="0">super</option>
												<option {% if request.GET.order == '1' %}selected{% endif %} value="1">user</option>
											</select>
										</div>
										<button type="submit"><i class='lnr lnr-magnifier'></i></button>
									</form>
								</li>
								<li><a href="{% url 'accounts:create_account' %}"><i style="font-size:15px;" class='lnr lnr-plus-circle'></i></a></li>
							</ul>
						</div>
					</div>

					<div class="panel-body">

						{% include "messages.html" %}

						{% if not object_list %}
							<h3>Nao existem contas cadastradas</h3>
						{% else %}
							<div class="table-responsive">
								<table class="table table-striped mb30">
									<thead>
										<tr>
										<th>#</th>
										<th>Nome</th>
										<th>E-mail</th>
										<th>Tipo</th>
										<th>Documento</th>
										<th>Status</th>
										<th></th>
										</tr>
									</thead>
									<tbody>
										{% for account in object_list %}
											<tr>
												<td>{{ account.pk }}</td>
												<td>{{ account.first_name }} {{ account.last_name }}</td>
												<td>{{ account.user.email }}</td>
												<td>{{ account.get_order_display }}</td>
												<td>{{ account.user.account.cpf }}</td>
												<td>
													{% if account.user.is_active %}
														<i style='color:green;' class='fa fa-check-circle'></i>
													{% else %}
														<i style='color:red;' class='fa fa-check-circle'></i>
													{% endif %}
												</td>
												<td>
													<a href='{{ account.active_account }}' class='btn btn-success btn-sm{% if account.user.account.status_payment %} disabled{% endif %}'>
														active
													</a>
												</td>
											</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>

							<nav><!--nav-->
								<ul class="pagination pagination-centered" style='margin: 5px 0 7px;'><!--ul pagination pagination-centered -->
									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled{% endif %}' href="?page=1{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title=""><<</a>
									</li>

									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled {% endif %}' href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title=""><</a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %} btn disabled{% endif %}' href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">></a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %}btn disabled{% endif %}' href="?page={{paginator.num_pages}}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">>></a>
									</li>
								</ul><!--ul pagination pagination-centered -->
							</nav><!--nav-->
							<small>{{ page_obj.number }} de {{paginator.num_pages}}</small>
						{% endif %}
					</div>
				</div>
			</div>

		</div><!-- END ROW LIST ACCOUNT -->
	</div><!-- END CONTAINER-FLUID -->
{% endblock %}