app/conf/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
	path('', RedirectView.as_view(url='/main/',permanent=True), name='index'),
    path('security/', admin.site.urls),
	path('main/', include(('main.urls', 'main'), namespace='main')),
	path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
	path('wallet/', include(('wallet.urls', 'wallet'), namespace='wallet')),
	path('i18n/', include('django.conf.urls.i18n')),
]

app/main/urls.py
from django.urls import path
from main.views import home, graphics, alerts, payment, balance, set_left_menu_session

urlpatterns=[
    path('', home, name='home'),
    path('graphics/', graphics, name='graphics'),
    path('alerts/', alerts, name='alerts'),
    path('payment/', payment, name='payment'),
    path('balance/', balance, name='balance'),
    path('set_left_menu_session/', set_left_menu_session, name='set_left_menu_session'),
]

app/wallet/urls.py
#encoding: utf-8

from django.urls import path
from wallet.views import (delete_debit, detail_debit, update_debit,
						list_debit, add_debit, delete_deposit, detail_deposit,
						update_deposit, list_deposit, add_deposit, delete_note,
						detail_note, update_note, list_note, add_note, update_status_note,
						teste)

urlpatterns = [
	#debit urls
	path('delete_debit/<pk>', delete_debit, name='delete_debit'),
	path('detail_debit/<pk>', detail_debit, name='detail_debit'),
	path('update_debit/<pk>', update_debit, name='update_debit'),
	path('list_debit/', list_debit, name='list_debit'),
	path('add_debit/', add_debit, name='add_debit'),

	#deposit urls
	path('delete_deposit/<pk>', delete_deposit, name='delete_deposit'),
	path('detail_deposit/<pk>', detail_deposit, name='detail_deposit'),
	path('update_deposit/<pk>', update_deposit, name='update_deposit'),
	path('list_deposit/', list_deposit, name='list_deposit'),
	path('add_deposit/', add_deposit, name='add_deposit'),

	#note urls
	path('delete_note/<pk>', delete_note, name='delete_note'),
	path('detail_note/<pk>', detail_note, name='detail_note'),
	path('update_note/<pk>', update_note, name='update_note'),
	path('list_note/', list_note, name='list_note'),
	path('add_note/', add_note, name='add_note'),
	path('update_status_note/<pk>', update_status_note, name='update_status_note'),

	path('teste/', teste, name='teste'),
]

app/wallet/models.py
from django.db import models
from accounts.models import Account
from django.db.models import Sum
from datetime import datetime
from django.urls import reverse


class DebitManager(models.Manager):

    def list_debits(self, user):
        qs = super(DebitManager, self).get_queryset()
        if not user.is_superuser and user.is_active:
            qs = qs.filter(account=user.account)
        elif user.is_superuser:
            qs = qs
        else:
            qs = qs.none()
        return qs

    def sum_debits(self, user):
        qs = super(DebitManager, self).get_queryset()
        if user.is_active:
            qs = qs.filter(account=user.account).aggregate(Sum('value')).get('value__sum') or 0

        return qs


class Debit(models.Model):

    id_debit = models.AutoField(primary_key=True, verbose_name=u'Cod Debit', db_column='id_debit')
    origin = models.CharField(verbose_name=u'Origem', db_column='origin', max_length=30, null=False, blank=False)
    value = models.DecimalField(max_digits=12, decimal_places=2, verbose_name=u'Valor', db_column='value',
    							null=False, blank=False)
    document = models.CharField(verbose_name=u'Documento', db_column='document', max_length=30, null=True, blank=True)
    account = models.ForeignKey(Account, verbose_name='Conta', related_name='debits_account',
                                on_delete=models.CASCADE, null=False)
    author = models.CharField(verbose_name=u'Autor', db_column='author', max_length=30, null=False, blank=False)
    date_releases = models.DateTimeField(verbose_name=u'Data do Debito', db_column='date_releases')
    description = models.TextField(db_column='description', blank=True, null=True, verbose_name=u'Descricao')
    created_at = models.DateTimeField(verbose_name=u'Data de criação', auto_now_add=True, db_column='date_created')
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')

    objects = DebitManager()

    def __unicode__(self):
        return (u'%s - %s') % (self.origin, self.value)

    def get_update_debit(self):
        return reverse('wallet:update_debit', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('wallet:detail_debit', kwargs={'pk': self.pk})

    def get_delete_debit(self):
        return reverse('wallet:delete_debit', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Debit'
        verbose_name_plural = 'Debit'
        ordering=['-created_at']
        db_table='debit'
        permissions = (
                ('add_new_debit', 'add debit'),
                ('list_new_debit', 'list debit'),
                ('delete_new_debit', 'delete debit'),
                ('change_new_debit', 'change debit'),
                ('detail_new_debit', 'detail debit'),
        )



class DepositManager(models.Manager):

    def list_deposits(self, user):
        qs = super(DepositManager, self).get_queryset()
        if not user.is_superuser and user.is_active:
            qs = qs.filter(account=user.account)
        elif user.is_superuser:
            qs = qs
        else:
            qs = qs.none()
        return qs

    def sum_deposits(self, user):
        qs = super(DepositManager, self).get_queryset()
        if user.is_active:
            qs = qs.filter(account=user.account).aggregate(Sum('value')).get('value__sum') or 0

        return qs


class Deposit(models.Model):

    id_deposit = models.AutoField(primary_key=True, verbose_name=u'Cod Deposit', db_column='id_deposit')
    origin = models.CharField(verbose_name=u'Origem', db_column='origin', max_length=30, null=False, blank=False)
    value = models.DecimalField(max_digits=12, decimal_places=2, verbose_name=u'Valor', db_column='value',
                                null=False, blank=False)
    document = models.CharField(verbose_name=u'Documento', db_column='document', max_length=30, null=True, blank=True)
    account = models.ForeignKey(Account, verbose_name='Conta', related_name='deposits_account',
                                on_delete=models.CASCADE, null=False)
    author = models.CharField(verbose_name=u'Autor', db_column='author', max_length=30, null=False, blank=False)
    date_releases = models.DateTimeField(verbose_name=u'Data do Deposito', db_column='date_releases')
    description = models.TextField(db_column='description', blank=True, null=True, verbose_name=u'Descricao')
    created_at = models.DateTimeField(verbose_name=u'Data de criação', auto_now_add=True, db_column='date_created')
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')

    objects = DepositManager()

    def __unicode__(self):
        return (u'%s - %s') % (self.origin, self.value)

    def get_update_deposit(self):
        return reverse('wallet:update_deposit', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('wallet:detail_deposit', kwargs={'pk': self.pk})

    def get_delete_deposit(self):
        return reverse('wallet:delete_deposit', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Deposit'
        verbose_name_plural = 'Deposit'
        ordering=['-created_at']
        db_table='deposit'
        permissions = (
                ('add_new_deposit', 'add deposit'),
                ('list_new_deposit', 'list deposit'),
                ('delete_new_deposit', 'delete deposit'),
                ('change_new_deposit', 'change deposit'),
                ('detail_new_deposit', 'detail deposit'),
        )



class NoteManager(models.Manager):

    def list_notes(self, user):
        qs = super(NoteManager, self).get_queryset()
        if not user.is_superuser and user.is_active:
            qs = qs.filter(account=user.account)
        elif user.is_superuser:
            qs = qs
        else:
            qs = qs.none()
        return qs


class Note(models.Model):

    id_note = models.AutoField(primary_key=True, verbose_name=u'Cod Note', db_column='id_note')
    title = models.CharField(verbose_name=u'TiTulo', db_column='title', max_length=30, null=False, blank=False)
    account = models.ForeignKey(Account, verbose_name='Conta', related_name='notes_account',
                                on_delete=models.CASCADE, null=False)
    author = models.CharField(verbose_name=u'Autor', db_column='author', max_length=30, null=False, blank=False)
    status_alert = models.BooleanField(verbose_name=u'Status Alert', default=False, db_column='status_alert')
    status_note = models.BooleanField(verbose_name=u'Status Note', default=True, db_column='status_note')
    description = models.TextField(db_column='description', blank=False, null=False, verbose_name=u'Descricao')
    date_note = models.DateTimeField(verbose_name=u'Data da Nota', db_column='date_note')
    created_at = models.DateTimeField(verbose_name=u'Data de criação', auto_now_add=True, db_column='date_created')
    updated_at = models.DateTimeField(verbose_name=u'Atualizado em', auto_now=True, db_column='updated_at')

    objects = NoteManager()

    def __unicode__(self):
        return (u'%s - %s') % (self.status_note, self.title)

    def get_delete_url(self):
        return reverse('wallet:delete_note', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('wallet:update_note', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('wallet:detail_note', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Note'
        verbose_name_plural = 'Note'
        ordering=['-created_at']
        db_table='note'
        permissions = (
                ('add_new_note', 'add note'),
                ('list_new_note', 'list note'),
                ('delete_new_note', 'delete note'),
                ('change_new_note', 'change note'),
                ('detail_new_note', 'detail note'),
        )

app/conf/templates/wallet/note/add_note.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}

{% block extra_styles %}
	<link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li><a href="{% url 'wallet:list_note' %}"><i class="fa fa-tags fa-fw"></i> Notas</a></li>
			<li class='active'><i class="fa fa-plus fa-fw"></i> Nova Nota</li>
		</ol>

		<div class="row" id="add_note">
			<div class="col-md-12">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Nova Nota</h3>
						<div class='right'>
							<ul class="list-inline">
								<li><a href='{% url "wallet:list_note" %}'><i style="font-size:15px;" class='lnr lnr-cross'></i></a></li>
							</ul>
						</div>
					</div>

					<div class="panel-body">
						{% include 'messages.html' %}

						<div class='col-md-12'>
							<div class="profile-detail">

								<form method='post' name='new_note'>
								{% csrf_token %}
									<div class='row'>
										<div class="form-group col-sm-3 {% if form.title.errors %}has-error{% endif %}">
											<label for="id_title">Título:</label>
											{{ form.title|placeholder:"Título" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.title.errors|join:"<br \>" }}</span>
										</div><!-- END ROW -->

										<ul class="list-inline ul_note_create">
											<li>
												<div class="form-group {% if form.status_alert.errors %}has-error{% endif %}">
													<label for="id_status_alert">Alerta:</label>
													<label class="switch">
														{{ form.status_alert|addcss:"form-control" }}
														<div class="slider round"></div>
													</label>
													<small class="text-muted">desligado/ligado</small>
												</div>
											</li>
										</ul>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-3 {% if form.date_note.errors %}has-error{% endif %}">
											<label for="id_date_note">Data da Nota:</label>
											{{ form.date_note|placeholder:"dd/mm/yyyy H:i" |addcss:"form-control" }}
										</div>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-6 {% if form.description.errors %}has-error{% endif %}">
											<label for="id_description">Nota:</label>
											{{ form.description|placeholder:"Descrição" |textarea:"5" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.description.errors|join:"<br \>" }}</span>
										</div>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-6">
											<button class='btn btn-primary' type="submit" name='add_note' id='id_add_note'>
											Salvar
											</button>

											<a class='btn btn-danger' href="{% url 'wallet:list_note' %}" name='close_add_note' id='id_close_note'>
											Fechar
											</a>
										</div>
									</div><!-- END ROW -->

								</form>

							</div>
						</div>
					</div>
				</div><!--END PANEL-->
			</div><!--END COL-MD-12-->
		</div><!-- END ROW -->
	</div><!-- END CONTAINER-FLUID -->
{% endblock %}

{% block extra_scripts %}
	<script src="{% static 'js/libs/moment.min.js' %}"></script>
	<script src="{% static 'js/libs/daterangepicker.js' %}"></script>
	<script src="{% static 'js/wallet.js' %}"></script>
{% endblock %}

app/conf/templates/wallet/note/list_note.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}

{% block extra_styles %}
	<link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li class='active'><i class="fa fa-tags fa-fw"></i> Notas</li>
		</ol>
		<!-- ROW LIST NOTE -->
		<div class="row" id="list_note">
			<div class="col-md-12">
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Notas</h3>
						<div class='right'>
							<form class="form-inline" method="get">
								<label class="sr-only" for="id_status_note">status_alert</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-tags" aria-hidden="true"></i>
									</div>
									<select class="form-control" name="status_alert" id="id_status_alert">
										<option {% if request.GET.status_alert == 'all' %}selected{% endif %} value="all">todos</option>
										<option {% if request.GET.status_alert == 'True' %}selected{% endif %} value="True">alerta</option>
										<option {% if request.GET.status_alert == 'False' %}selected{% endif %} value="False">notas</option>
									</select>
								</div>

								<label class="sr-only" for="id_status_note">status_note</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-tags" aria-hidden="true"></i>
									</div>
									<select class="form-control" name="status_note" id="id_status_note">
										<option {% if request.GET.status_note == 'all' %}selected{% endif %} value="all">todos</option>
										<option {% if request.GET.status_note == 'True' %}selected{% endif %} value="True">abertas</option>
										<option {% if request.GET.status_note == 'False' %}selected{% endif %} value="False">fechadas</option>
									</select>
								</div>

								<label class="sr-only" for="date">Data</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-calendar"></i>
									</div>
									<input type="text" class="form-control" name='date' id="date" placeholder="dd/mm/yyyy" value="{% if request.GET.date %}{{ request.GET.date }}{% endif %}">
								</div>

								<button type="submit"><i class='lnr lnr-magnifier'></i></button>

								<a href='{% url "wallet:add_note" %}'><i style="font-size:15px;" class='lnr lnr-plus-circle'></i></a>
							</form>
						</div>
					</div>

					<div class="panel-body">
						{% include "messages.html" %}

						{% if not object_list %}
							<div class='empty-object'>
								<center>
									<h3>Não existem lançamentos de depósitos cadastrados</h3>
								</center>
							</div>
						{% else %}
							<ul class="list-unstyled todo-list">
								{% for note in object_list %}
									<li class='{% if not note.status_note %}completed{% endif %}'>
										<label id='note-list-input' class="control-inline fancy-checkbox">
											<input id='{{ note.pk }}' type="checkbox" {% if not note.status_note %}checked{% endif %}><span></span>
										</label>
										<p>
											<span class="title">{{ note.title }}</span>
											<span class="label label-primary"><i class='fa fa-edit'></i></span>
											{% if note.status_alert %}
												<span class="label label-success"><i class='fa fa-warning'></i></span>
											{% endif %}
											<span class="short-description">{{ note.description }}</span>
											<span class="date">{{ note.date_note | date:"d/m/Y H:i" }}</span>
										</p>
										<div class="controls">
											<a href="{{ note.get_absolute_url }}"><i class="lnr lnr-pencil"></i></a>
											<a href="{{ note.get_delete_url }}"><i class="lnr lnr-trash"></i></a>
										</div>
									</li>
								{% endfor %}
							</ul>

							<nav>
								<ul class="pagination pagination-centered" style='margin: 5px 0 7px;'><!--ul pagination pagination-centered -->
									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled{% endif %}' href="?page=1" title=""><<</a>
									</li>

									<li>
										<a class='{% if page_obj.has_previous %}btn{% else %} btn disabled {% endif %}' href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}" title=""><</a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %} btn disabled{% endif %}' href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}" title="">></a>
									</li>

									<li>
										<a class='{% if page_obj.has_next %}btn{% else %}btn disabled{% endif %}' href="?page={{paginator.num_pages}}" title="">>></a>
									</li>
								</ul><!--ul pagination pagination-centered -->
							</nav><!--nav-->
							<small>{{ page_obj.number }} de {{paginator.num_pages}}</small>
						{% endif %}
					</div>

				</div>
			</div>
		</div>
		<!-- END ROW LIST NOTE -->
	</div>
{% endblock %}
{% block extra_scripts %}
	<script src="{% static 'js/libs/moment.min.js' %}"></script>
	<script src="{% static 'js/libs/daterangepicker.js' %}"></script>
	<script src="{% static 'js/wallet.js' %}"></script>
{% endblock %}

app/conf/templates/wallet/note/modal_test.html
{% load formtags %}

	<div class="modal-header">
		<button aria-hidden="true" data-dismiss="modal" class="close" type="button">
			<i style="font-size:15px;" class='lnr lnr-cross'></i>
		</button>
		<h4 class="modal-title">Adicionar Notas</h4>
	</div>
	<div class="modal-body">
		<div class="row" id="note">
				<div class="col-md-12">
				<!-- TODO LIST -->
						{% if messages %}
							{% for message in messages %}
								<div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible"{% endif %} role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									<strong>{{ message.tags }}:</strong> {{ message }}.
								</div>
							{% endfor %}
						{% endif %}

						{% if form.errors %}
							<div class="alert alert-danger">
								<button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
								<strong>Error: </strong>
								{% for field, error in form.errors.items %}
									{% if field != '__all__' %}{{ field }}{% endif %}
										{{ error | striptags }}<br />
									{% endfor %}
							</div>
						{% endif %}
					</div>
							<div class="col-md-12 col-md-offset-2">
								<form method='post' class="form-modal-note" id="id_new_note" name='new_note' action="{% url 'wallet:add_note' %}">
									{% csrf_token %}
									<div class='row'>
										<div class="form-group col-sm-4 {% if form.title.errors %}has-error{% endif %}">
											<label for="id_title">Título:</label>
											{{ form.title|placeholder:"Título" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.title.errors|join:"<br \>" }}</span>
										</div>

										<ul class="list-inline ul_note_create">
											<li style="margin-left: 60px;">
												<div class="form-group {% if form.status_alert.errors %}has-error{% endif %}">
													<label for="id_status_alert">Alerta:</label>
													<label class="switch">
														{{ form.status_alert|addcss:"form-control" }}
														<div class="slider round"></div>
													</label>
													<small class="text-muted">desligado/ligado</small>
												</div>
											</li>
										</ul>
									</div>

									<div class='row'>
										<div class="form-group col-sm-4 {% if form.date_note.errors %}has-error{% endif %}">
											<label for="id_date_note">Data da Nota:</label>
											{{ form.date_note|placeholder:"dd/mm/yyyy H:i" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.date_note.errors|join:"<br \>" }}</span>
										</div>
									</div>

									<div class='row'>
										<div class="form-group col-sm-6 {% if form.description.errors %}has-error{% endif %}">
											<label for="id_description">Nota:</label>
											{{ form.description|placeholder:"Descrição" |textarea:"5" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.description.errors|join:"<br \>" }}</span>
										</div>
									</div>

									<div class='row'>
										<div class="col-md-6">
										<div class="form-group">
											<!--<button onclick="send_form('{% url 'wallet:add_note' %}', 'id_new_note', 'id_save_note');" class='btn btn-primary' type="button" name='save_note' id='id_save_note'>
												Salvar
											</button>-->
											<button type="submit" class="btn btn-primary">
												Salvar
											</button>

											<button class="btn btn-danger" aria-hidden="true" data-dismiss="modal" type="button">
												Fechar
											</button>
										</div>
										</div>
									</div>

								</form>


				<!-- END TODO LIST -->
			</div>
	</div>
</div>

app/conf/templates/wallet/note/update_note.html
{% extends 'base.html' %}
{% load static %}
{% load formtags %}

{% block extra_styles %}
	<link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<ol class="breadcrumb">
			<li><a href="{% url 'main:home' %}"><i class="fa fa-home fa-fw"></i> Inicio</a></li>
			<li><a href="{% url 'wallet:list_note' %}"><i class="fa fa-tags fa-fw"></i> Notas</a></li>
			<li class='active'><i class="fa fa-edit fa-fw"></i> Editar Notas</li>
		</ol>

		<!-- ROW UPDATE NOTE -->
		<div class="row" id="note_update">
			<div class="col-md-12">

				<div class="panel">

					<div class="panel-heading">
						<h3 class="panel-title">Editar Notas</h3>
						<div class='right'>
							<ul class="list-inline">
								<li>
									<a href='{% url "wallet:list_note" %}'>
										<i class='lnr lnr-cross'></i>
									</a>
								</li>
							</ul>
						</div>
					</div><!-- END PANEL-HEADING -->

					<div class="panel-body">
						{% include "messages.html" %}

						<div class='col-md-12'>
							<div class="profile-detail">

								<form method='post' name='update_note' id="id_update_note">
								{% csrf_token %}
									<div class='row'>
										<div class="form-group col-sm-3 {% if form.title.errors %}has-error{% endif %}">
											<label for="id_title">Título:</label>
											{{ form.title|placeholder:"Título" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.title.errors|join:"<br \>" }}</span>
										</div>

										<ul class="list-inline ul_note_create">
											<li>
												<div class="form-group {% if form.status_alert.errors %}has-error{% endif %}">
													<label for="id_status_alert">Alerta:</label>
													<label class="switch">
														{{ form.status_alert|addcss:"form-control" }}
														<div class="slider round"></div>
													</label>
													<small class="text-muted">desligado/ligado</small>
												</div>
											</li>
											<li>
												<div class="form-group {% if form.status_note.errors %}has-error{% endif %}">
													<label for="id_status_note">Status:</label>
													<label class="switch">
														{{ form.status_note|addcss:"form-control" }}
														<div class="status_slider round"></div>
													</label>
													<small class="text-muted">fechada/aberta</small>
												</div>
											</li>
										</ul>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-3 {% if form.date_note.errors %}has-error{% endif %}">
											<label for="id_date_note">Data da Nota:</label>
											{{ form.date_note|placeholder:"dd/mm/yyyy H:i" |addcss:"form-control" }}
										</div>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-6 {% if form.description.errors %}has-error{% endif %}">
											<label for="id_description">Nota:</label>
											{{ form.description|placeholder:"Descrição" |textarea:"5" |addcss:"form-control" }}
											<span class="error text-danger">{{ form.description.errors|join:"<br \>" }}</span>
										</div>
									</div><!-- END ROW -->

									<div class='row'>
										<div class="form-group col-sm-6">
											<button class='btn btn-primary' type="submit" name='update_note' id='id_update_note'>
												Editar
											</button>

											<a class='btn btn-danger' href="{% url 'wallet:list_note' %}" name='close_update_note' id='id_close_update_note'>
												Fechar
											</a>
										</div>
									</div><!-- END ROW -->

								</form>
							</div><!-- PROFILE-DETAIL -->
						</div><!-- COL-MD-12 -->

					</div><!-- END PANEL-BODY -->
				</div><!-- END PANEL -->

			</div><!-- COL-MD-12 -->
		</div>
		<!-- END ROW UPDATE NOTE -->

	</div><!-- END CONTAINER-FLUID -->
{% endblock %}

{% block extra_scripts %}
	<script src="{% static 'js/libs/moment.min.js' %}"></script>
	<script src="{% static 'js/libs/daterangepicker.js' %}"></script>
	<script src="{% static 'js/wallet.js' %}"></script>
{% endblock %}